<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <!-- "latest" works on local PC but not in build pipeline; Visual Studio version difference? Whatever, preview it is. -->
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <!--
	  We added Span-based variant methods to several APIs. Code that uses those methods or implements the
	  affected interfaces (or abstract classes) will not be backward compatible. There are also several
	  methods in DotNetUtilities dealing with ECDsa which is only available from net47.

	  TODO: Use suppressions for each individual case of version-dependent methods.
    -->
    <NoWarn>$(NoWarn);CP0002;CP0005;CP0006</NoWarn>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lextm.SharpSnmpLib" Version="12.5.7" />
    <PackageReference Include="Microsoft.TSS" Version="2.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CustomLogger\CustomLogger.csproj" />
    <ProjectReference Include="..\EndianTools\EndianTools.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <!--For now disable the PSN ticket verification as many keys are still undocumented -->
    <DefineConstants>$(DefineConstants);DISABLE_PSN_XI5_VERIFICATION</DefineConstants>
  </PropertyGroup>
</Project>
